# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64ac7a26420071cfd30639aa4686e0a523e4665dfc7993f3a2c41fd7bcdfa6aa4b3db8a29de20712a1d7072bdb26a90165099edf0a7a58171eb7905b6ecbe49e

test:
  secret_key_base: 219a816fbfd80bb85faa21f984d6562a641a3f3ab95ed40fe57b079fd0594f8ff8322c8d1ae60cff37727259c66f265a4d2446f593b825c83ff5c1cf8722349a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
